// Auto-generated by: npm run db:types
// Manually defined here as a starting point — run the command above after connecting Supabase

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface CampaignItem {
  name: string;
  quantity: number;
  unit: string;
  unit_cost_ghs: number;
  [key: string]: Json | undefined;
}

export interface ProfileRow {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  role: "investor" | "admin";
  phone: string | null;
  created_at: string;
  updated_at: string;
}

export interface CampaignRow {
  id: string;
  slug: string;
  title: string;
  description: string;
  story: string;
  location: string;
  region: string;
  target_amount: number;
  raised_amount: number;
  currency: "GHS" | "USD";
  status: "draft" | "active" | "funded" | "completed";
  cover_image_url: string | null;
  gallery_urls: string[];
  items_needed: CampaignItem[];
  beneficiaries_count: number | null;
  end_date: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface ContributionRow {
  id: string;
  user_id: string;
  campaign_id: string;
  amount: number;
  currency: "GHS" | "USD";
  paystack_reference: string;
  paystack_transaction_id: string | null;
  status: "pending" | "success" | "failed";
  message: string | null;
  anonymous: boolean;
  created_at: string;
}

export interface ImpactReportRow {
  id: string;
  campaign_id: string;
  title: string;
  summary: string;
  photos_urls: string[];
  items_delivered: CampaignItem[];
  beneficiaries_reached: number;
  published: boolean;
  created_by: string;
  created_at: string;
}

export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: any;
        Insert: any;
        Update: any;
        Relationships: any[];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: "investor" | "admin";
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: "investor" | "admin";
          phone?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: "investor" | "admin";
          phone?: string | null;
        };
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          slug: string;
          title: string;
          description: string;
          story: string;
          location: string;
          region: string;
          target_amount: number;
          raised_amount: number;
          currency: "GHS" | "USD";
          status: "draft" | "active" | "funded" | "completed";
          cover_image_url: string | null;
          gallery_urls: string[];
          items_needed: any;
          beneficiaries_count: number | null;
          end_date: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          slug: string;
          title: string;
          description: string;
          story: string;
          location: string;
          region?: string;
          target_amount: number;
          currency?: "GHS" | "USD";
          status?: "draft" | "active" | "funded" | "completed";
          cover_image_url?: string | null;
          gallery_urls?: string[];
          items_needed?: any;
          beneficiaries_count?: number | null;
          end_date?: string | null;
          created_by: string;
        };
        Update: {
          slug?: string;
          title?: string;
          description?: string;
          story?: string;
          location?: string;
          region?: string;
          target_amount?: number;
          currency?: "GHS" | "USD";
          status?: "draft" | "active" | "funded" | "completed";
          cover_image_url?: string | null;
          gallery_urls?: string[];
          items_needed?: any;
          beneficiaries_count?: number | null;
          end_date?: string | null;
          created_by?: string;
        };
        Relationships: [];
      };
      contributions: {
        Row: {
          id: string;
          user_id: string;
          campaign_id: string;
          amount: number;
          currency: "GHS" | "USD";
          paystack_reference: string;
          paystack_transaction_id: string | null;
          status: "pending" | "success" | "failed";
          message: string | null;
          anonymous: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          campaign_id: string;
          amount: number;
          currency?: "GHS" | "USD";
          paystack_reference: string;
          paystack_transaction_id?: string | null;
          status?: "pending" | "success" | "failed";
          message?: string | null;
          anonymous?: boolean;
        };
        Update: {
          user_id?: string;
          campaign_id?: string;
          amount?: number;
          currency?: "GHS" | "USD";
          paystack_reference?: string;
          paystack_transaction_id?: string | null;
          status?: "pending" | "success" | "failed";
          message?: string | null;
          anonymous?: boolean;
        };
        Relationships: [];
      };
      impact_reports: {
        Row: {
          id: string;
          campaign_id: string;
          title: string;
          summary: string;
          photos_urls: string[];
          items_delivered: any;
          beneficiaries_reached: number;
          published: boolean;
          created_by: string;
          created_at: string;
        };
        Insert: {
          campaign_id: string;
          title: string;
          summary: string;
          photos_urls?: string[];
          items_delivered?: any;
          beneficiaries_reached?: number;
          published?: boolean;
          created_by: string;
        };
        Update: {
          campaign_id?: string;
          title?: string;
          summary?: string;
          photos_urls?: string[];
          items_delivered?: any;
          beneficiaries_reached?: number;
          published?: boolean;
          created_by?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      campaign_stats: {
        Row: {
          campaign_id: string;
          total_contributions: number;
          unique_investors: number;
          progress_percent: number;
        };
      };
    };
    Functions: {
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: "investor" | "admin";
      campaign_status: "draft" | "active" | "funded" | "completed";
      contribution_status: "pending" | "success" | "failed";
      currency: "GHS" | "USD";
    };
  };
};

// Convenience types
export type Profile = ProfileRow;
export type Campaign = CampaignRow;
export type Contribution = ContributionRow;
export type ImpactReport = ImpactReportRow;
